/*
Write a program RandomGaussian that prints a random number r drawn from the Gaussian distribution. One way to do so is to use the Box–Muller formula r = sin(2*pi*v)*(-2*lnu)^1/2 where u and v are real numbers between 0 and 1 generated by the Math.random() method.
*/

public class GuassianRandomNumber {
	public static void main(String[] args) {
		double sin = Math.sin(2 * Math.PI * Math.random());
		double log = Math.sqrt(-2 * Math.log(Math.random()));

		System.out.println("r = " + sin * log);
	}
}
